### ISSUE TITLE
Discord services, accounts and gold spam.

### ISSUE THREAD

**Issue by OffensiveExile** [IamReallyOverrated/Runelite_ChatFilter#3]
Removes spam from bots spamming services, accounts or gold spam. Could probably do with a touch up as I don't know regex all that well but it gets the majority of it after standing in W2 for some time. Works best with accent stripper enabled.

Pattern:
`(?i)d.sc.rd.gg.+((?i)services|(?i)accounts|(?i)gold|(?i)secure|(?i)infern.+)`

Test Cases Used:
```
Dìscord,gg/rúnestore - C.H.E.A.P.E.S.T Accounts w/ Inferno Capes: Mains,
Dìscord,gg/rúnestore - Services: C.H.E.A.P.E.S.T and Safest Blood Torva!
Discord,gg/rúnestore - C.H.E.A.P.E.S.T Accounts w/ Inferno Capes: Mains,
Discord,gg/rúnestore - Services: C.H.E.A.P.E.S.T and Safest Blood Torva!
Discord.gg/rúnestore - C.H.E.A.P.E.S.T Accounts w/ Inferno Capes: Mains,
Discord.gg/rúnestore - Services: C.H.E.A.P.E.S.T and Safest Blood Torva!
Discord.Gg/runemarket - Cheapest Gold, Accounts & Services with 24/7 Support!
Discord.Gg/runemarket - We provide: Minigames, Quests, Skills / Infernal capes.
```

**Comment by Psicoses** [comment]
It looks good overall, some changes I would make

- The (?i) for case insensitivity is only needed once in the beginning
- Add ^ in the beginning to only match discord.gg in the beginning.

`(?i)^d.sc.rd.gg.+(services|accounts|gold|secure|infern.+)`

I added it to the untested branch for now. Along with 'runemarket' and 'rúnestore'. 
Thanks for the contribution!
