### ISSUE TITLE
Remove S.C.A.M and S.A.F.E chat bots

### ISSUE THREAD

**Issue by spychopat** [IamReallyOverrated/Runelite_ChatFilter#6]
Hello,
I would suggest to add these two words in the filter to block these kind of messages :
S.C.A.M
S.A.F.E
![image](https://github.com/IamReallyOverrated/Runelite_ChatFilter/assets/16687705/0dc417a2-dcca-4f9d-a086-191cf1798a0b)

Nobody is going to write it like this beside the chat bots anyway.
I'm not sure for the semantic of it, i mean, how to write it in the filter, so i'm just suggesting the words.

And btw, thanks for the great filter. Before that i used the plugin called "Spam filter" but this method is much simpler and much more efficient.

**Comment by spychopat** [comment]
oh, there is also the word
A.V.O.I.D
![image](https://github.com/IamReallyOverrated/Runelite_ChatFilter/assets/16687705/028a8839-1ecd-4071-9cce-b7c21dc5f2c9)

**Comment by Psicoses** [comment]
The regex's that were requested have been added to the testing branch. After about a day I'll migrate them over to master. Thanks @lewisclark for the commit https://github.com/IamReallyOverrated/Runelite_ChatFilter/pull/8.
