### ISSUE TITLE
Buy/Sell filter from own repo

### ISSUE THREAD

**Issue by tfemby** [IamReallyOverrated/Runelite_ChatFilter#7]
This regex is something I've had in my filter that covers I've seen the bots which say something along the line of, "Buying Ely 1b" etc. I haven't updated this particular regex since just before TOA came out so it doesn't have any of the newer higher priced items. The bots that do spam using these keywords have (thankfully) become rarer to see but I still do encounter them.

```
^.*((someone )?(sell me( your all)?|trade me)?|(anyone|no one) here have|(Looking to )?Buy(in(g)?)?( all)?|what you offer for|big chance to win( a)?) (t(wisted)?( )?bow|dwh|kodai wand|scythe( of vitur)?|ancestral set|(ghrazi )?rapier|dragon( )?hunter (c(ross| )+?bow|lance)|bandos( set)?|arma(dyl)?( set|c(ross|( )?bow)?)?|harmonised orb|sang(uinesti)?( staff)?|dhcb|d(ragon)? (claws(s)?|warhammer)|inquisitor(s)? set( / any pieces)?|(arcane|ely(sian)?|spectral)( spirit shield)?|bank|(valuable|good|expensive)?( )?items|most rares|torva( )?(set|items|parts)?|(volatile|harmoni(s|z)+ed|eldritch)?( orb)?|(thi|3)+rd age( item(s?)?)?)(([?]+| for|sell me one now|i will pay|,)+)? (\d{2,4} *[kmb](il+)?|max (cash|stack|gp)|over ge price|very good offer|paying good)?(!|.|,|\?)?.*$
```

Taking a look through the regex that you have, I feel like this could be used as an expansion to line 71. This also has some overlap with a lot of the `Doubling money and scams` section overall.

I'm not entirely sure how useful this behemoth of a regex could help but I thought it might be useful. I'm not entirely certain that it would even match up to most peoples regex standards haha

**Comment by Psicoses** [comment]
This is actually something I've been procrastinating. I see these bots pretty often, but they're spam isn't necessarily bot specific. So that regex seems like the only real good solution. So I'll add it under 71 for now, and if need be reduce it or modify it. Thanks!

**Comment by tfemby** [comment]
No worries! I actually re-read my issue and realised that I shouldn't write these messages when tired. I'm happy to give back to a project that's done a better job than the hacked together regex's I've been using.

Just a question of curiosity, if I want to add more items to that particular regex, should I post another issue with the commits of just like... copy and paste it again into the issue itself? Don't mind working with either tbh
